/**
 * The startup preflight — wired for real, and fatal.
 *
 * With cwd set to the target repo and settingSources ["user","project","local"],
 * supportedAgents() returns the five design-* subagents and supportedCommands()
 * returns `design`. If either is missing the target repo was never val-inited, and
 * the pipeline would degrade to general-purpose agents — an agent carrying the full
 * tool set and none of the discipline. That is the precise failure /design refuses
 * to run into, so Studio refuses to start into it either.
 *
 * settingSources matters: without it the SDK loads no filesystem settings, the
 * repo's .claude/agents/* are never discovered, and the preflight would report a
 * missing pipeline for a repo that is in fact configured correctly.
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { query } from "@anthropic-ai/claude-agent-sdk";
import type { PreflightResult } from "@valiify/studio-shared";
import { readValConfig } from "../target-repo.ts";
import { REQUIRED_AGENTS, REQUIRED_COMMANDS } from "./types.ts";

/** A prompt stream that yields nothing and closes on demand — the session is opened only to ask it questions. */
function idlePrompt(): { stream: AsyncIterable<never>; close: () => void } {
  let release!: () => void;
  const closed = new Promise<void>((r) => (release = r));
  async function* stream(): AsyncGenerator<never> {
    await closed;
  }
  return { stream: stream(), close: release };
}

/**
 * The Gate 0 check that the generated agents belong to THIS library: their header
 * records the config they were generated from. Agents generated for another repo
 * carry another library's class map, methodology path and package name, and produce
 * output that looks right and was composed against the wrong library.
 */
async function agentLibrary(targetRepo: string): Promise<string | undefined> {
  const text = await readFile(
    join(targetRepo, ".claude", "agents", "design-concept-architect.md"),
    "utf8",
  ).catch(() => null);
  if (!text) return undefined;
  return /GENERATED by @valiify\/val-core@\S+ from val\/config\.json \(library:\s*([^)]+)\)/i.exec(text)?.[1]?.trim();
}

export async function runPreflight(targetRepo: string): Promise<PreflightResult> {
  const started = Date.now();
  const base = {
    at: new Date().toISOString(),
    targetRepo,
    requiredAgents: [...REQUIRED_AGENTS],
    requiredCommands: [...REQUIRED_COMMANDS],
  };

  let configLibrary: string | undefined;
  try {
    configLibrary = (await readValConfig(targetRepo)).config.library.name;
  } catch (err) {
    return {
      ...base,
      ok: false,
      foundAgents: [],
      missingAgents: [...REQUIRED_AGENTS],
      foundCommands: [],
      missingCommands: [...REQUIRED_COMMANDS],
      durationMs: Date.now() - started,
      error: (err as Error).message,
    };
  }

  const prompt = idlePrompt();
  const q = query({
    prompt: prompt.stream,
    options: {
      cwd: targetRepo,
      // Without these three the repo's own .claude/agents and .claude/commands are
      // never loaded, and the preflight would fail a correctly configured repo.
      settingSources: ["user", "project", "local"],
    },
  });

  try {
    const [agents, commands] = await Promise.all([q.supportedAgents(), q.supportedCommands()]);
    const foundAgents = agents.map((a) => a.name);
    const foundCommands = commands.map((c) => c.name);
    const missingAgents = REQUIRED_AGENTS.filter((a) => !foundAgents.includes(a));
    const missingCommands = REQUIRED_COMMANDS.filter((c) => !foundCommands.includes(c));
    const lib = await agentLibrary(targetRepo);
    const libraryMatches = lib && configLibrary ? lib === configLibrary : undefined;

    return {
      ...base,
      ok: missingAgents.length === 0 && missingCommands.length === 0 && libraryMatches !== false,
      foundAgents: foundAgents.filter((a) => a.startsWith("design-")),
      missingAgents,
      foundCommands: foundCommands.filter((c) => c === "design" || c.startsWith("design")),
      missingCommands,
      agentLibrary: lib,
      configLibrary,
      libraryMatches,
      durationMs: Date.now() - started,
    };
  } catch (err) {
    return {
      ...base,
      ok: false,
      foundAgents: [],
      missingAgents: [...REQUIRED_AGENTS],
      foundCommands: [],
      missingCommands: [...REQUIRED_COMMANDS],
      configLibrary,
      durationMs: Date.now() - started,
      error: (err as Error).message,
    };
  } finally {
    prompt.close();
    try {
      q.close();
    } catch {
      /* already closed */
    }
  }
}

/** The message Studio dies with. Loud on purpose — a quiet degrade is the failure mode. */
export function preflightFailureMessage(r: PreflightResult): string {
  const lines = [
    "PREFLIGHT FAILED — refusing to start.",
    `  target repo: ${r.targetRepo}`,
  ];
  if (r.error) lines.push(`  error: ${r.error}`);
  if (r.missingAgents.length) lines.push(`  missing subagents: ${r.missingAgents.join(", ")}`);
  if (r.missingCommands.length) lines.push(`  missing commands: /${r.missingCommands.join(", /")}`);
  if (r.libraryMatches === false) {
    lines.push(
      `  agent/library mismatch: agents were generated for "${r.agentLibrary}", val/config.json says "${r.configLibrary}"`,
    );
  }
  lines.push(
    "",
    "The target repo was never val-inited (or was inited for a different library).",
    "Without the five design-* subagents and /design, the pipeline degrades to",
    "general-purpose agents — the full tool set and none of the discipline. That is",
    "the exact failure /design refuses to run into, so Studio will not start into it.",
    "",
    `  cd '${r.targetRepo}' && npx val-init`,
  );
  return lines.join("\n");
}
